---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Set Java 8 package for RedHat.
      ansible.builtin.set_fact:
        java_packages:
          - openjdk-17-jdk
      when: ansible_os_family == "RedHat"

    - name: Set Java 17 package for Ubuntu.
      ansible.builtin.set_fact:
        java_packages:
          - openjdk-17-jdk
      when: ansible_os_family == "Ubuntu"

    - name: Set Java 17 package for Debian.
      ansible.builtin.set_fact:
        java_packages:
          - openjdk-17-jdk
      when: ansible_os_family == "Debian"

    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Install dependencies (Debian).
      ansible.builtin.apt:
        name:
          - openjdk-17-jre-headless
          - ca-certificates-java
        state: present
      when: ansible_distribution == "Debian"

  roles:
    - role: shaneholloman.java
    - role: shaneholloman.solr
